---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
    - name: frontend
      image: rkalluru/frontend
#      ports:                            this is pod level -- to expose frontend to outside world
#        - containerPort: 80
#          hostPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-roboshop
spec:
  type: NodePort           # this service level --- to expose frontend to outside world
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
