apiVersion: v1
kind: Pod
metadata:
  name: 03-service
  labels: 03-service
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: service-03 # any name
spec:
  selector:
    name: 03-service #the selector name and labels name should be same... to conncet pod & svc we use selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80